name: Xgrid Automation
on:
  [push]
    
jobs:
  build:
    permissions:
        id-token: write    # Job to connect to Identity Token to receive the token
        contents: read     # Read access to the repository
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
